MOCK_BACKORDERS = [
    {
        "supplier_code": "SUP-1001",
        "supplier_name": "Apex Components",
        "plant_code": "NL01",
        "planner_code": "PLN-A",
        "part_number": "BRG-4400",
        "po_number": "4500102391",
        "due_date": "2026-04-03",
        "ordered_qty": 1200,
        "received_qty": 300,
        "open_qty": 900,
        "is_backorder": True,
        "backorder_days": 14,
        "backorder_status": "Critical",
    },
    {
        "supplier_code": "SUP-2044",
        "supplier_name": "Nordic Fasteners",
        "plant_code": "DE02",
        "planner_code": "PLN-B",
        "part_number": "BOLT-M8-22",
        "po_number": "4500102450",
        "due_date": "2026-04-10",
        "ordered_qty": 5000,
        "received_qty": 3600,
        "open_qty": 1400,
        "is_backorder": True,
        "backorder_days": 7,
        "backorder_status": "Open",
    },
    {
        "supplier_code": "SUP-3320",
        "supplier_name": "Kanto Plastics",
        "plant_code": "US03",
        "planner_code": "PLN-C",
        "part_number": "CAP-8821",
        "po_number": "4500102598",
        "due_date": "2026-03-25",
        "ordered_qty": 800,
        "received_qty": 0,
        "open_qty": 800,
        "is_backorder": True,
        "backorder_days": 23,
        "backorder_status": "Critical",
    },
    {
        "supplier_code": "SUP-1001",
        "supplier_name": "Apex Components",
        "plant_code": "NL01",
        "planner_code": "PLN-D",
        "part_number": "SEAL-102",
        "po_number": "4500102677",
        "due_date": "2026-04-15",
        "ordered_qty": 200,
        "received_qty": 80,
        "open_qty": 120,
        "is_backorder": True,
        "backorder_days": 2,
        "backorder_status": "Watch",
    },
]
